#!/bin/bash

bat=${BLOCK_INSTANCE:-0}
threshold=14
precision=2

charge_status=$(cat /sys/class/power_supply/BAT${bat}/status)

pow_now=$(cat /sys/class/power_supply/BAT${bat}/power_now)
watts=$(bc <<< "scale=${precision}; ${pow_now} / 1000000")
watts_int=$(echo ${watts} | awk -F '.' '{print $1}')

if [ -z "${watts}" ]; then
  exit 1
fi

# color
if [ "${charge_status}" = "Charging" ]; then
  color="#FF00FF"
elif [ "${charge_status}" = "Discharging" ]; then
  if [ ${watts_int} -ge ${threshold} ]; then
    color="#FFFF00"
  fi
else
  color=""
fi

# output
cat << EOF
{
    "full_text": "${watts}W",
    "color": "${color}"
}
EOF
