#!/bin/bash
#
# Requires xset (xorg-xset) to be installed

state=$(xset q | awk '/Caps Lock/ {print $4}')

# color
if [ ${state} = 'on' ]; then
  color="#00FFFF"
  echo 1 > /sys/class/leds/tpacpi::kbd_backlight/brightness
  exit_code=33
else
  color="#424242"
  echo 0 > /sys/class/leds/tpacpi::kbd_backlight/brightness
  exit_code=0
fi

# full text, short text, color
echo "CAPS"
echo "CAPS"
echo "${color}"

exit ${exit_code}
