#!/bin/bash
#
# Requires xset (xorg-xset) to be installed

state=$(xset q | awk '/Caps Lock/ {print $4}')

# full text
echo "CAPS"

# short text
echo "CAPS"

# color
if [ ${state} = 'on' ]; then
  echo "#00FFFF"
  exit 33;
else
  echo "#424242"
  exit 0;
fi
