#!/bin/bash

_refresh()
{
    pkill -RTMIN+35 i3blocks
}

_get_temp()
{
    busctl --user get-property rs.wl-gammarelay / rs.wl.gammarelay Temperature
}

_set_temp()
{
    busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q $1
}


_update_temp()
{
    busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateTemperature n $1
}

case $BLOCK_BUTTON in
  3) _set_temp 6500 && _refresh ;; # right click
  4) _update_temp 200 && _refresh ;; # scroll up
  5) _update_temp -200 && _refresh ;; # scroll down
esac

temp=$(_get_temp | cut -d ' ' -f 2)

if [ -z "${temp}" ]; then
    exit 0;
fi

# output
cat << EOF
{
    "full_text": "CT ${temp}"
}
EOF
