#!/bin/sh

refresh()
{
    pkill -RTMIN+30 i3blocks
}

get_temp()
{
    busctl --user -- get-property rs.wl-gammarelay / rs.wl.gammarelay Temperature | cut -d ' ' -f 2
}

set_temp()
{
    busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q $1 > /dev/null
}

update_temp()
{
    busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateTemperature n $1 > /dev/null
}

case $BLOCK_BUTTON in
  3) set_temp 6500 && refresh ;; # right click
  4) update_temp 200 && refresh ;; # scroll up
  5) update_temp -200 && refresh ;; # scroll down
esac

temp=$(get_temp)

if [ -z "${temp}" ]; then
    exit 0;
fi

# output
cat << EOF
{
    "full_text": "CT ${temp}K"
}
EOF
