#!/bin/bash

cur_uj=$(cat /sys/class/powercap/intel-rapl:0/energy_uj)
prev_uj_file=$HOME/.prev_cpu_uj
prev_uj=$(cat ${prev_uj_file})
echo ${cur_uj} > ${prev_uj_file}

time_diff=$1
precision=2
watts_bc=$(bc <<< "scale=${precision}; (${cur_uj}-${prev_uj})/(${time_diff}*1000000)")
watts=$(printf "%.2f" "${watts_bc}")

if [ -z "${watts}" ]; then
  exit 0
fi

# output
cat << EOF
{
    "full_text": "CPU ${watts}W"
}
EOF
