#!/bin/bash

# https://stackoverflow.com/a/64182793
freq=$(awk '
    length==6 {
        printf("%.0f%s\n", $0/10^3, "MHz"); next
    } length==7 {
        printf("%.1f%s\n", $0/10^6, "GHz")
    }' /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
)

if [ -z "${freq}" ]; then
  exit 0
fi

# output
cat << EOF
{
    "full_text": "${freq}"
}
EOF
