#!/usr/bin/perl
use strict;
use warnings;

my $V = 0;
my $I = 0;

open (SENSORS, 'sensors -u |') or die;
while (<SENSORS>) {
    if (/in0_input: (.+)/) {
        $V = $1;
    } elsif (/curr1_input: (.+)/) {
        $I = $1;
    }
}
close(SENSORS);

printf "%.2fW\n", $I * $V;
