#!/bin/bash

cur_uj=$(cat /sys/class/powercap/intel-rapl:0/energy_uj)
prev_uj_file=/tmp/i3blocks-cpu_power-prev_cpu_uj
prev_uj=$(cat ${prev_uj_file})
echo ${cur_uj} > ${prev_uj_file}

time_diff=$1
watts_raw=$(bc <<< "scale=2; (${cur_uj}-${prev_uj})/(${time_diff}*1000000)")
watts_int=$(printf "%.0f" ${watts_raw})

if [ -z "${watts_raw}" ]; then
  exit 0
fi

if [[ ${watts_int} -lt 10 ]]; then
    watts=$(printf "%.2f" "${watts_raw}")
else
    watts=$(printf "%.1f" "${watts_raw}")
fi

# color
if [[ ${watts_int} -ge 15 ]]; then
    color="#FFFF00"
elif [[ ${watts_int} -ge 30 ]]; then
    color="#FF0000"
else
    color=""
fi

# output
cat << EOF
{
    "full_text": "CPU ${watts}W"
    "color": "${color}"
}
EOF
