#!/bin/bash

# https://stackoverflow.com/a/64182793
freq=$(awk 'length==6{printf("%.0f MHz\n", $0/10^3); next} length==7{printf("%.3f GHz\n", $0/10^6)}' /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)

if [ -z "${freq}" ]; then
  exit 0
fi

# full text
echo "${freq}"

# short text
echo "${freq}"

# color
