#!/bin/bash

capacity_path="/sys/class/power_supply/sony_controller_battery_*/capacity"
if [ -f $capacity_path ]; then
    capacity="$(cat $capacity_path)%"
else
    exit 0;
fi

# output
cat << EOF
{
    "full_text": "DS3 ${capacity}"
}
EOF
