#!/bin/bash

# First check if the gpu is active; otherwise `nvidia-smi` will wake it
runtime_status=$(cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status)
if [[ ! "$runtime_status" =~ active ]]; then
    echo "GPU off"
    exit 0
fi

nvidia_smi=$(nvidia-smi)
power=$(rg '(\d+)W\s*\/\s*(\d+)W' -or '$1' <<< "${nvidia_smi}")
temperature=$(rg '(\d+)C' -or '$1' <<< "${nvidia_smi}")

printf "GPU %dW  %d°C\n" $power $temperature
