#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"
LOW_THRESH="${1:-15}" # color will turn yellow under this threshold (default: 15%)

awk -v type=$TYPE -v low_thresh=$LOW_THRESH '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	# full text / short text
	if (type == "swap") {
		printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
		printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
    } else {
		printf("%.1fG\n", mem_free/1024/1024)
		printf("%.1fG\n", mem_free/1024/1024)
    }

	# color (if less than LOW_THRESH %)
    if (mem_free/mem_total * 100 < low_thresh) {
        print("#FFFF00")
    }
}
' /proc/meminfo
