#!/bin/bash
# From acleverpun on github

# Shows ip address of a given interface
#
# @param {String} interface: The network interface to check

interface="${BLOCK_INSTANCE:-"eth0"}"
net_path=/sys/class/net
interface_path=$(echo ${net_path}/${interface})
# Expand wildcard interfaces
interface=${interface_path#${net_path}/}

state="$(cat ${interface_path}/operstate)"

if [[ ${state} != "up" ]]; then
    exit 0
fi

ipaddr=$(ip addr show wlan0 | awk 'match($0, "inet (.+)/", groups) {print groups[1]}')

if [[ ${BLOCK_INSTANCE} == "wlan*" ]]; then
    quality=$(grep ${interface} /proc/net/wireless | awk '{print int($3 * 100 / 70)}')
    ssid="$(iw ${interface} link | grep SSID | cut -d ' ' -f 2)"
    IFS=' ' read -r down up <<< $(\
        iw ${interface} link \
        | grep bitrate \
        | cut -d " " -f 3 \
        | paste -sd " " \
    )
    speed=$(printf "%d↓ %d↑" "${down}" "${up}")
    text="${quality}% ${speed} Mb/s (${ssid})"
elif [[ ${BLOCK_INSTANCE} == "enp*" ]]; then
    quality=100
    speed=$(cat ${interface_path}/speed)
    text="${speed} Mb/s"
else
    exit 0
fi

# color
if [[ -z "${ipaddr}" ]]; then
    color="#FF0000"
elif [[ ${quality} -ge 80 ]]; then
    color="#00FF00"
elif [[ ${quality} -ge 40 ]]; then
    color=""
else
    color="#FFFF00"
fi

# output
cat << EOF
{
    "full_text": "${text}",
    "color": "${color}"
}
EOF
