#!/bin/bash
volume_str=$(wpctl get-volume @DEFAULT_SINK@)
percent=$(awk '{print $2 * 100}' <<< ${volume_str})
muted=$(awk 'index($3, "MUTED")' <<< ${volume_str})
label=$([ "${muted}" ] && echo "MUTE" || echo "VOL")

# color
if [ -n "${muted}" ]; then
    color="#FFFF00"
else
    color=""
fi

# output
cat << EOF
{
    "full_text": "${label} ${percent}%",
    "color": "${color}"
}
EOF
