#!/bin/bash
volume_str=$(wpctl get-volume @DEFAULT_SINK@)
percent=$(awk '{print $2 * 100}' <<< ${volume_str})
muted=$(awk 'index($3, "MUTED")' <<< ${volume_str})
label=$([ "${muted}" ] && echo "MUTE" || echo "VOL")

# full text
echo "${label} ${percent}%"

# short text
echo "${label} ${percent}%"

# color
if [ -n "${muted}" ]; then
    echo "#FFFF00"
fi
