# DO NOT SYMLINK
# NOTE:
# With default parameters:
# * Occasionally, the trackpoint reporting rate will drastically decrease.
#   * Touching/moving the touchpad (unreliably?) seems to reset this.
# * The trackpoint reporting rate will sligthly decrease if the touchpad is
#   touched at the same time.
#
# Parameters
# ----------
# * elantech_smbus
#   * This doesn't appear to do anything in this context; it sounds like it
#     only applies for elan touchpads.
# * synaptics_intertouch
#   * Setting this to 1 drastically reduces the reporting rate for the
#     touchpad, but seems to mitigate the issue of the trackpoint occasionally
#     slowing down. Instead, the touchpad will occasionally become unreliable
#     (cancelled inputs; less responsive; lol --- it looks like this is due to
#     detecting and hanging on "GESTURE_HOLD_BEGIN" events).
# * proto
#   * bare, imps, exps
#       * These seem to give the illusion of a higher reporting rate since the
#         trackpoint moves slower, but it looks like these mostly just disable
#         features enabled the the proper drives (touchpad multi-touch,
#         independent libinput settings, etc.)
# * rate, resolution
#   * These don't really seem to do anything and it looks like they'll be
#     clamped to an allowed range, but they also probably shouldn't hurt.
options psmouse rate=1000 resolution=400
