context.modules = [
{   name = libpipewire-module-loopback
    args = {
        capture.props = {
            node.passive = true
            node.dont-reconnect = true
        }
        playback.props = {
            node.dont-reconnect = true
            node.passive = true
        }
    }
}
]
